pipeline { 
    agent any          

     tools { maven 'maven 3.6.1' }

    stages{ 
        stage("build"){ 
            steps{ 
                 when { changeset "**/worker/**" }
                 echo 'Compiling worker app' 
                 dir('worker') { sh 'mvn compile' }
            } 
        } 
        stage("test"){ 
            steps{ 
                 when { changeset "**/worker/**" }
                 echo 'Running Unit Tests on worker app' 
                 dir('worker') { sh 'mvn clean test' }
            } 
        } 
        stage("package"){ 
            steps{ 
                 when { changeset "**/worker/**"
                        branch master }
                 echo 'Packaging worker app' 
                 dir('worker') { sh 'mvn package -DskipTests' }
            } 
        } 
    }        
    post{         

        always{      
             archiveArtifacts artifacts: '**/target/*.jar', fingerprint:true
             echo 'Building multibranch pipeline for worker is completed..' 
        } 
    } 
}
